version: "3"

# DEVELOPMENT ONLY
# this is not a secure configuration

volumes:
  mongostorage:
    driver: local

services:
  keyfieldhome:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keyfield_dev_homeserver
    restart: "no"
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "True"
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:8008:8008"

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: "/data/db"
    volumes:
      - mongostorage:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_SITE_BASEURL: "/admin/"
      # ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: "keyfield_local_dev"
