
[server]
name = "KeyField Test Homeserver"
external_addresses = [
  "http://localhost:5000",
  "http://localhost:8008"
]
listen_port = 8008
username = "system"

[users]
public_registration = true
admin_keys = {}
reserved_names = [
  "admin", "administrator", "owner",
  "system", "server", "homeserver",
]

[db]
address = "127.0.0.1"
port = 27017
database_name = "keyfield_dev"

[federation]
# option to globally disable communication with other homeservers
federate = true
# useful for running a completely private homeserver:
# requires users to be registered to pull identity blocks
public_profiles = true
# verifykeys of homeservers to block all federation with:
blocked_peers_keys = []
# addresses which will not be federated to, regardless of keys
blocked_peers_addresses = []
# attempt to update profiles from their own homeserver when they are retrieved
auto_update_nonlocal_profiles = true
