
[server]
name = "KeyField Test Homeserver"
external_addresses = [
  "http://localhost:5000",
  "http://localhost:8008"
]
listen_port = 8008
username = "system"

[users]
public_registration = true
admin_keys = {}
reserved_names = [
  "admin", "administrator", "owner",
  "system", "server", "homeserver",
]

[db]
address = "127.0.0.1"
port = 27017
database_name = "keyfield_dev"

[federation]
blocked_peers_keys = []
blocked_peers_addresses = []
# auto_update_profiles = true
